apiVersion: batch/v1
kind: CronJob
metadata:
  name: feast-materialize-crypto
  namespace: crypto
spec:
  # Run every 5 minutes for testing
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: feast-materialize
              image: satzweb/feast-runner:latest   # you built earlier
              imagePullPolicy: Always

              # 1️⃣ THIS IS CRITICAL → SET WORKING DIR TO YOUR FEAST REPO ROOT
              workingDir: /app/feast_repo/crypto_features/feature_repo

              command: ["/bin/sh", "-c", "./jobs/run_materialization.sh"]

              env:
                # --- Feast Offline Store (Postgres) ---
                - name: PGHOST
                  value: "postgres.infra.svc.cluster.local"
                - name: PGPORT
                  value: "5432"
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: postgres-credentials
                      key: username
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-credentials
                      key: password
                - name: PGDATABASE
                  value: "feast"

                # --- Redis Online Store ---
                - name: REDIS_HOST
                  value: "redis-master.infra.svc.cluster.local"
                - name: REDIS_PORT
                  value: "6379"

                # Optional safety (recommended)
                - name: FEAST_USAGE
                  value: "local"

              resources:
                requests:
                  cpu: "100m"
                  memory: "256Mi"
                limits:
                  cpu: "500m"
                  memory: "512Mi"
