apiVersion: batch/v1
kind: CronJob
metadata:
  name: feast-materialize-crypto
  namespace: crypto
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 600
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: feast-materialize
              image: satzweb/feast-runner:latest1
              imagePullPolicy: Always

              workingDir: /app/feast_repo/crypto_features/feature_repo

              command: ["/bin/sh", "-c", "sh ./jobs/run_materialization.sh"]

              env:

                # --- Postgres ---
                - name: PGHOST
                  value: "postgres-service.infra.svc.cluster.local"
                - name: PGPORT
                  value: "5432"
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: postgres-credentials
                      key: username
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-credentials
                      key: password
                - name: PGDATABASE
                  value: "feast_offline"

                # --- Redis ---
                - name: REDIS_HOST
                  value: "redis-master.infra.svc.cluster.local"
                - name: REDIS_PORT
                  value: "6379"

                # --- MINIO OFFLINE STORE ACCESS ---
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: minio-credentials
                      key: MINIO_ACCESS_KEY
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: minio-credentials
                      key: MINIO_SECRET_KEY
                - name: AWS_REGION
                  value: "us-east-1"

                - name: AWS_S3_ENDPOINT
                  value: "http://minio-service.infra.svc.cluster.local:9000"

                - name: FEAST_S3_ENDPOINT_URL
                  value: "http://minio-service.infra.svc.cluster.local:9000"

                - name: AWS_ENDPOINT_URL_S3
                  value: "http://minio-service.infra.svc.cluster.local:9000"


                # Recommended
                - name: AWS_S3_ALLOW_UNSAFE_RENAME
                  value: "true"

                - name: AWS_S3_ALLOW_UNSIGNED_PAYLOAD
                  value: "true"   
                - name: AWS_S3_ADDRESSING_STYLE
                  value: "path"

                - name: AWS_SIGNATURE_VERSION
                  value: "s3v4"



              resources:
                requests:
                  cpu: "100m"
                  memory: "256Mi"
                limits:
                  cpu: "500m"
                  memory: "512Mi"
