apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: crypto
type: Opaque
data:
  AWS_ACCESS_KEY_ID: bWluaW9hZG1pbg==
  AWS_SECRET_ACCESS_KEY: bWluaW9hZG1pbjEyMw==
  AWS_REGION: dXMtZWFzdC0x
